
<!DOCTYPE html>
<html>
<head>
    <title>home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../../styles/gallery.css">
    <link rel="stylesheet" href="../../styles/news_window.css">
    <link href='https://fonts.googleapis.com/css?family=Bungee Shade' rel='stylesheet'>

</head>
<body>
    <header role="banner">
        <img style="width:100%;height:200px;margin:0;" src="../../image/saint%20francis%20of%20assisi.jpg">
    </header>
    <div class="topnav">
        <ul>
            
            <li><a href="../../?controller=reg_ops/register">Sign Up</a></li>
            <?php if(!isset($_SESSION['logged_in'])): ?>
                <li><a href="../../?controller=auth_ops/login_panel">Login</a></li>
            <?php elseif(isset($_SESSION['logged_in'])): ?>
                <li><a href="../../?controller=auth_ops/logout">logout</a></li>
                <li><a><?php echo $_SESSION['logged_in'] ?></a></li>
            <?php endif; ?>
            <li class="dropdown">
              <a href="javascript:void(0)" class="dropbtn">Activities</a>
              <div class="dropdown-content">
                <div class="row">
                  <center> <p>Click to view the activities of various units of the church</p></center>
                  <div class="column side1">

                    <span>COMMUNITIES</span>
                    <a href="#">Igede Catholic Community</a>
                    <a href="#">Arewa Catholic Community</a>
                    <a href="#">Niger Delta Communities</a>
                    <a href="#">Igbo Catholic Community</a>
                </div>
                <div class="column middle1">
                    <span>SOCITIES</span>
                    <a href="#">Board of Lectors</a>
                    <a href="#">St Vincent De Paul</a>
                    <a href="#">Charismatic Renewal Movement</a>
                </div>
                <div class="column side1">   
                    <span>Organizations</span>
                    <a href="#">C.M.O</a>
                    <a href="#">C.W.O</a>
                    <a href="#">C.Y.O.N</a>
                </div>
            </div>
        </div>
    </li>

    <li class="dropdown">
      <a href="javascript:void(0)" class="dropbtn">Announcements</a>
      <div class="dropdown-content">
        <div class="row">

          <div class="column side1">
            <span>General Parish Announcements</span>
            <a href="../../?controller=announce_ops/general_view_con">View All</a>
            <?php if(isset($_SESSION['logged_in'])): ?>
              <a href="../../?controller=announce_ops/general_add_con">Add New</a>
              <a href="../../?controller=announce_ops/general_delete_con">Delete Some</a>
          <?php endif; ?>
      </div>

      <div class="column side1">
        <span>Marriage Banns</span>
        <a href="../../?controller=announce_ops/marriage_bann_show_con">View Banns</a>
        <?php if(isset($_SESSION['logged_in'])): ?>
          <a href="../../?controller=announce_ops/marriage_bann_add_con">Add New Bann</a>
          <a href="../../?controller=announce_ops/marriage_bann_del_con">Delete Bann</a>
      <?php endif; ?>

  </div>

  <div class="column side1">
    <span>Church Collections</span>
    <a href="../../?controller=announce_ops/collection_view_con">View Collections</a>
    <?php if(isset($_SESSION['logged_in'])): ?>
      <a href="../../?controller=announce_ops/collection_add_con">Add Collections</a>
      <a href="../../?controller=announce_ops/collection_delete_con">Delete Collections</a>
  <?php endif; ?>
</div>

</div>
</div>
</li>


<li> <a href="../../?controller=home/home">Send bulk sms</a></li>
<li> <a href="../../?controller=gallery_ops/gallery_home">Galllery</a></li>

<li><a href="#">News</a></li>
<li><a href="../../?controller=home/general_home">Home</a></li>
</ul>
</div>
<main role="main">
   
    <div class="row">
        <div class="column">
            <img src="../../image/books_in_church_190501.jpg" width="300" height="300" onclick="openModal();currentSlide(1)" class="hover-shadow">

        </div>
        <div class="column"> 
            <img src="../../image/church_sculpture_faith_230555.jpg" width="300" height="300" onclick="openModal();currentSlide(2)" class="hover-shadow">
        </div>
        <div class="column" >
            <img src="../../image/saint%20francis2.jpg" width="300" height="300" onclick="openModal();currentSlide(3)" class="hover-shadow">
        </div>
        <div class="column">
            <img src="../../image/facade_gothic_churches_241012.jpg" width="300" height="300" onclick="openModal();currentSlide(4)" class="hover-shadow"> 
        </div>
        <div class="column">
            <img src="../../image/images17.jpg" width="300" height="300" onclick="openModal();currentSlide(5)" class="hover-shadow"> 
        </div>
        <div class="column">
            <img src="../../image/images18.jpg" width="300" height="300" onclick="openModal();currentSlide(6)" class="hover-shadow"> 
        </div>
        <div class="column">
            <img src="../../image/images20.jpg" width="300" height="300" onclick="openModal();currentSlide(7)" class="hover-shadow"> 
        </div>
        <div class="column">
            <img src="../../image/jesus_christ_son_of_god_264072.jpg"  width="300" height="300" onclick="openModal();currentSlide(8)" class="hover-shadow"> 
        </div>
        <div class="column" >
            <img src="../../image/images21.jpg" width="300" height="300" onclick="openModal();currentSlide(9)" class="hover-shadow"> 
        </div>
        <div class="column">
            <img src="../../image/jesus_on_the_cross_192549.jpg" width="300" height="300" onclick="openModal();currentSlide(10)" class="hover-shadow"> 
        </div>
        <div class="column" >
            <img src="../../image/images11.jpg" width="300" height="300" onclick="openModal();currentSlide(11)" class="hover-shadow"> 
        </div>
        <div class="column" >
            <img src="../../image/st-francis-of-assisi-19.jpg" width="300" height="300" onclick="openModal();currentSlide(12)" class="hover-shadow"> 
        </div>
    </div>

    <div id="myModal" class="modal">
        <span class="close cursor" onclick="closeModal()">&times;</span>
        <div class="modal-content">

            <div class="mySlides">
                <div class="numbertext">1 / 12</div>
                <img src="../../image/books_in_church_190501.jpg" width="100%" height="500" >
            </div>

            <div class="mySlides">
                <div class="numbertext">2 / 12</div>
                <img src="../../image/church_sculpture_faith_230555.jpg"  width="100%" height="500">
            </div>

            <div class="mySlides">
                <div class="numbertext">3 / 12</div>
                <img src="../../image/saint%20francis2.jpg"width="100%" height="500">
            </div>

            <div class="mySlides">
                <div class="numbertext">4 / 12</div>
                <img src="../../image/facade_gothic_churches_241012.jpg" width="100%" height="500">
            </div>
            <div class="mySlides">
                <div class="numbertext">5 / 12</div>
                <img src="../../image/images17.jpg" width="100%" height="500">
            </div>
            <div class="mySlides">
                <div class="numbertext">6 / 12</div>
                <img src="../../image/images18.jpg" width="100%" height="500">
            </div>
            <div class="mySlides">
                <div class="numbertext">7 / 12</div>
                <img src="../../image/images20.jpg" width="100%" height="500">
            </div>
            <div class="mySlides">
                <div class="numbertext">8 / 12</div>
                <img src="../../image/jesus_christ_son_of_god_264072.jpg"  width="100%" height="500">
            </div>
            <div class="mySlides">
                <div class="numbertext">9 / 12</div>
                <img src="../../image/images21.jpg"width="100%" height="500">
            </div>
            <div class="mySlides">
                <div class="numbertext">10 / 12</div>
                <img src="../../image/images14.jpg"  width="100%" height="500">
            </div>
            <div class="mySlides">
                <div class="numbertext">11 / 12</div>
                <img src="../../image/images11.jpg"   width="100%" height="500">
            </div>
            <div class="mySlides">
                <div class="numbertext">12 / 12</div>
                <img src="../../image/st-francis-of-assisi-19.jpg"S  width="100%" height="500">
            </div>

            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
            <center>

                <div class="caption-container">
                    <p id="caption"></p>
                </div>

                <div class="column">
                    <img class="demo" src="../../image/books_in_church_190501.jpg" width="200" height="200" onclick="currentSlide(1)" alt="khcohnillkfflfklbnfnbflflnbflblfbfn.fnklhhnifhoglhjnoglfkgflgfgjhnolhginsfklgnksgnfkgnkfnfflknklf,bfbnflkbnfkdkkdhkgbnkdfkbnklgbknkdNature">
                </div>

                <div class="column">
                    <img class="demo" src="../../image/church_sculpture_faith_230555.jpg" width="200" height="200" onclick="currentSlide(2)" alt="Trolltunga">
                </div>

                <div class="column">
                    <img class="demo" src="../../image/saint%20francis2.jpg" width="200" height="200" onclick="currentSlide(3)" alt="Mountains">
                </div>

                <div class="column">
                    <img class="demo" src="../../image/facade_gothic_churches_241012.jpg"  width="200" height="200"n onclick="currentSlide(4)" alt="Lights">
                </div>
                <div class="column">
                    <img class="demo" src="../../image/images17.jpg" width="200" height="200"  onclick="currentSlide(5)" alt="Lights">
                </div>
                <div class="column">
                    <img class="demo" src="../../image/images18.jpg" width="200" height="200"  onclick="currentSlide(6)" alt="Lights">
                </div>
                <div class="column">
                    <img class="demo" src="../../image/images20.jpg" width="200" height="200 "   onclick="currentSlide(7)" alt="Lights">
                </div>
                <div class="column">
                    <img class="demo" src="../../image/jesus_christ_son_of_god_264072.jpg" width="200" height="200"  onclick="currentSlide(8)" alt="Lights">
                </div>
                <div class="column">
                    <img class="demo" src="../../image/images21.jpg" width="200" height="200"  onclick="currentSlide(9)" alt="Lights">
                </div>
                <div class="column">
                    <img class="demo" src="../../image/images14.jpg" width="200" height="200"  onclick="currentSlide(10)" alt="Lights">
                </div>
                <div class="column">
                    <img class="demo" src="../../image/images11.jpg" width="200" height="200"   onclick="currentSlide(11)" alt="Lights">
                </div>
                <div class="column">
                    <img class="demo" src="../../image/st-francis-of-assisi-19.jpg" width="200" height="200"   onclick="currentSlide(12)" alt="Lights">
                </div>
                
            </center> 

        </div>
    </div>
</main>
<footer role="footer">
    <div class="footer">
     &copy;Lawrant Group
 </div>
</footer>
<script type="text/javascript" src="../../scripts/gallery.js">
</script>
</body>
</html>

