<!-- This is a view for home page. It has links to other sub categories -->
<!-- It's controller is "home.php" -->

<!DOCTYPE html>
<html lang="en">
<head>
    <title>home1</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../../styles/announcements.css">
    <link rel="stylesheet" href="../../styles/news_window.css">
    <link href='https://fonts.googleapis.com/css?family=Bungee Shade' rel='stylesheet'>
    <style>
        #comments
        {
            position: relative;
            overflow: auto; 
            height: 500px;
            width:100%;
        }
    </style>
</head>
<body>
    <header role="banner">
      <div class="column middle"> <img   src="../../image/saint%20francis%20of%20assisi.jpg">
      </div> 
      <div class="search">
        <input type="text"  placeholder="Search..."><input type="submit"></div>
        
        <div class="topnav">
          <ul>
            <li><a href="../../?controller=reg_ops/register">Sign Up</a></li>
            <!-- This should later link to a user profile page -->
            <?php if(!isset($_SESSION['logged_in'])): ?>
                <li><a href="../../?controller=auth_ops/login_panel">Login</a></li>
            <?php elseif(isset($_SESSION['logged_in'])): ?>
                <li><a href="../../?controller=auth_ops/logout">logout</a></li>
                <li><a><?php echo $_SESSION['logged_in'] ?></a></li>
            <?php endif; ?>
            <li class="dropdown">
              <a href="javascript:void(0)" class="dropbtn">Activities</a>
              <div class="dropdown-content">
                <div class="row">

                  <div class="column side1">

                    <span>COMMUNITIES</span>
                    <a href="#">Igede Catholic Community</a>
                    <a href="#">Arewa Catholic Community</a>
                    <a href="#">Niger Delta Communities</a>
                    <a href="#">Igbo Catholic Community</a>
                </div>
                <div class="column middle1">
                    <span>SOCITIES</span>
                    <a href="#">Board of Lectors</a>
                    <a href="#">St Vincent De Paul</a>
                    <a href="#">Charismatic Renewal Movement</a>
                </div>
                <div class="column side1">   
                    <span>Organizations</span>
                    <a href="#">C.M.O</a>
                    <a href="#">C.W.O</a>
                    <a href="#">C.Y.O.N</a>
                </div>
            </div>
        </div>
    </li>

    <li class="dropdown">
      <a href="javascript:void(0)" class="dropbtn">Announcements</a>
      <div class="dropdown-content">
        <div class="row">

            <div class="column side1">
                <span>General Parish Announcements</span>
                <a href="../../?controller=announce_ops/general_view_con">View All</a>
                <a href="../../?controller=announce_ops/general_add_con">Add New</a>
                <a href="../../?controller=announce_ops/general_delete_con">Delete Some</a>
            </div>

            <div class="column side1">
                <span>Marriage Banns</span>
                <a href="../../?controller=announce_ops/marriage_bann_show_con">View Banns</a>
                <a href="../../?controller=announce_ops/marriage_bann_add_con">Add New Bann</a>
                <a href="../../?controller=announce_ops/marriage_bann_del_con">Delete Bann</a>
            </div>

            <div class="column side1">
                <span>Church Collections</span>
                <a href="../../?controller=announce_ops/collection_view_con">View Collections</a>
                <a href="../../?controller=announce_ops/collection_add_con">Add Collections</a>
                <a href="../../?controller=announce_ops/collection_delete_con">Delete Collections</a>
            </div>
        </div>
    </div>
</li>

<li><a href="#">News</a></li>
<li><a href="../../?controller=home/general_home">Home</a></li>

</ul>
</div>
</header>
<main role="main">
    <marquee><span class="slide" style="color:blue">SAINT FRANCIS CATHOLIC CHURCH GALADIMAWA</span></marquee>
    <div class="column side">

        <div class="table">
            <div id="comments">
                <table>
                    <caption><h1>MARRIAGE BANNS</h1></caption>



                    <tr>
                        <th>Sponsus' Information</th>
                        <th>Sponsa's Information</th>
                    </tr>

                    <tr><th colspan="2" style="background-color:biege;">1st Call</th></tr>
                    <?php
                    foreach ($banns as $bann):
                        if($bann['call_number']=='1st') :
                            ?>
                        <tr>
                            <td><?php

                                echo "Name:".$bann['sponsus'].'<br>';
                                echo "Father: ".$bann['sponsus_father'].'<br>';
                                echo "Mother: ".$bann['sponsus_mother'].'<br>';
                                echo "Native: ".$bann['sponsus_native'].'<br>';
                                ?>
                            </td>

                            <td><?php
                                echo 'Name: '.$bann['sponsa'].'<br>';
                                echo 'Father: '.$bann['sponsa_father'].'<br>';
                                echo 'Mother: '.$bann['sponsa_mother'].'<br>';
                                echo 'Native: '.$bann['sponsa_native'].'<br>';
                                ?>
                            </td>
                        </tr>

                    <?php endif; ?>
                <?php endforeach; ?>

                <tr><th colspan="2" style="background-color:biege;">2nd Call</th></tr>
                <?php
                foreach ($banns as $bann):
                    if($bann['call_number']=='2nd') :
                        ?>
                    <tr>
                        <td><?php

                            echo "Name:".$bann['sponsus'].'<br>';
                            echo "Father: ".$bann['sponsus_father'].'<br>';
                            echo "Mother: ".$bann['sponsus_mother'].'<br>';
                            echo "Native: ".$bann['sponsus_native'].'<br>';
                            ?>
                        </td>

                        <td><?php
                            echo 'Name: '.$bann['sponsa'].'<br>';
                            echo 'Father: '.$bann['sponsa_father'].'<br>';
                            echo 'Mother: '.$bann['sponsa_mother'].'<br>';
                            echo 'Native: '.$bann['sponsa_native'].'<br>';
                            ?>
                        </td>
                    </tr>

                <?php endif; ?>
            <?php endforeach; ?>

            <tr><th colspan="2" style="background-color:biege;">3rd Call</th></tr>
            <?php
            foreach ($banns as $bann):
                if($bann['call_number']=='3rd') :
                    ?>
                <tr>
                    <td><?php

                        echo "Name:".$bann['sponsus'].'<br>';
                        echo "Father: ".$bann['sponsus_father'].'<br>';
                        echo "Mother: ".$bann['sponsus_mother'].'<br>';
                        echo "Native: ".$bann['sponsus_native'].'<br>';
                        ?>
                    </td>

                    <td><?php
                        echo 'Name: '.$bann['sponsa'].'<br>';
                        echo 'Father: '.$bann['sponsa_father'].'<br>';
                        echo 'Mother: '.$bann['sponsa_mother'].'<br>';
                        echo 'Native: '.$bann['sponsa_native'].'<br>';
                        ?>
                    </td>
                </tr>

            <?php endif; ?>
        <?php endforeach; ?>


    </table>
</div>
</div>
<div class="slide show">
    <img class="mySlides w3-animate-fading" src="../../image/images16.jpg" style="width:100%; height:500px;" >
    <img class="mySlides w3-animate-fading" src="../../image/images20.jpg" style="width:100%; height:500px;">
    <img class="mySlides w3-animate-fading" src="../../image/images11.jpg" style="width:100%;height:500px;">
    <img class="mySlides w3-animate-fading" src="../../image/france_st_michel_church_217281.jpg" style="width:100%;height:500px;">
    <img class="mySlides w3-animate-fading" src="../../image/church_mosaic_194351.jpg" style="width:100%;height:500px;">
    <img class="mySlides w3-animate-fading" src="../../image/jesus_christ_son_of_god_264072.jpg" style="width:100%;height:500px;">
    <img class="mySlides w3-animate-fading" src="../../image/facade_gothic_churches_241012.jpg" style="width:100%;height:500px;">
    <img class="mySlides w3-animate-fading" src="../../image/images19.jpg" style="width:100%;height:500px;">
    <img class="mySlides w3-animate-fading" src="../../image/images17.jpg" style="width:100%;height:500px;">
</div>       
</div>

<div class="column middle">
    <div class="announcement-div">

        <div class="table">
            <div id="comments">
                <table>
                    <caption><h1>General Announcement</h1></caption>



                    <tr>
                        <th>Announcer</th>
                        <th>Event</th>
                        <th>Venue</th>
                        <th>Date</th>
                        <th>Time</th>
                    </tr>

                    <?php foreach ($general as $announcement): ?>

                        <tr>

                            <td><?php echo $announcement['announcer'].'<br>';?></td>
                            <td><?php echo $announcement['event'].'<br>';?></td> 
                            <td><?php echo $announcement['venue'].'<br>';?></td>
                            <td><?php echo $announcement['date'].'<br>'; ?></td> 
                            <td><?php echo $announcement['time'].'<br>'; ?></td> 
                        </tr>


                    <?php endforeach; ?>
                </table>

            </div>

        </div>

        <div class="table">
            <div id="comments">
                <table>
                    <caption><h1>CHURCH COLLECTIONS</h1></caption>



                    <tr>
                        <th>S/N</th>
                        <th>Purpose of collection</th>
                        <th>Date</th>
                    </tr>

                    <?php 
                    $x = 1;
                    foreach ($collection as $announcement): ?>


                    <tr>

                        <td><?php echo $x++ ?> </td>
                        <td><?php echo $announcement["purpose"] ?> </td>
                        <td><?php echo $announcement["day"] ?> </td>

                    </tr>


                <?php endforeach; ?>
            </table>

        </div>
        <div class="prayers">
            <h2>PRAYER AFTER COMMUNION</h2>

            <b>O Sacrament Most Holy (3X)</b>
            <b>ANIMA CHRISTI</b>
            Soul of Christ, sanctify me
            Body of Christ, save me
            Blood of Christ, inebriate me
            Water from the side of Christ, wash me
            Passion of Christ, strengthen me
            O good Jesus, hear me
            Within Thy wounds hide me
            Suffer me not to be separated from you
            From the malicious enemy defend me
            At the hour of my death call me
            And bid me come to you so that with
            you saints I may praise you forever and 
            ever. Amen.
            <hr>
            <h2>PRAYER FOR CHURCH BUILDING PROJECT</h2>

            Almighty God, today we the members of
            Saint Francis  Galadimawa Catholic Church
            gathered "united in the spirit to thank you
            for your love and mercy, that provide us with
            the strength to work together as a family".
            O Lord, in thanksgiving to you, we desire to
            build a befiting place of worship, as an 
            offering of praise and testimony of our 
            comforter and greatest friend, our faith in
            you we ask for your grace and presence as we 
            embark on this divine project.
            Heavenly Father, give us strength to stand 
            firm and never look back even in the face of
            challenges, but remain strong in your name.
            Bless our members and benefactors for the
            support they shall give in this noble cause.
            Holy Spirit, Our comforter, guide and inspire
            us as strive to achieve this purpose.
            O Blessed Virgin Mary, we ask for your
            intercessions and prayers.
            We make our prayer through Christ our 
            Lord Amen.
            "Most Sacred Heart of Jesus-have mercy on us"
            "Immaculate Heart of Mary - pray for us"
            "St. Joseph Our Protector - pray for us"
            "St. Linus - pray for us"
            "St. Francis of Assisi - pray for us"
            "St. Augustine - pray for us"
            <hr>
            <h2>THE CREED</h2>
            I believe in one God, the Father Almighty,
            maker of heaven and earth, of all things
            visible and invisible. I believe in one
            LordvJesus Christ, the only begotten son
            of God, born of the Father befor all ages
            God from God, Light from Light, True God
            from True God begotten, not made, 
            consubstantial with the Father, through 
            Him all things were made,for us men and 
            for our salvation He came down from heaven,
            and by the Holy Spirit was incarnate of the
            Virgin Mary, and became man.
            For our sake He was crucified under 
            Pontus Pilate, He suffered death and was
            buried, and rose again on the third day in 
            accordance with the scriptures. He ascended
            into heaven and is seated at the right of the
            Father. He will come again in Glory to judge
            the living and the dead and His Kingdom will
            have no end. 
            I believe in the Holy Spirit, the Lord the 
            giver of life, who proceeds from the Father
            and the Son, who with the Father and the
            Son is adored and Glorified, who has spoken
            through the prophets.
            I believe in one, holy, Catholic and 
            Apostolic Church, I confess one Baptism for
            the forgiveness of sins and I look forward 
            to the ressurrection of the dead and life of
            the world to come. 
            Amen.
        </div>
    </div>
</div>
</div>
</main>
<footer role="footer">
    <div class="footer">
     &copy;Lawrant Group
 </div>
</footer>
<script>

    var myIndex = 0;
    carousel();

    function carousel() {
        var i;
        var x = document.getElementsByClassName("mySlides");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";  
        }
        myIndex++;
        if (myIndex > x.length) {myIndex = 1}    
            x[myIndex-1].style.display = "block";  
        setTimeout(carousel, 9000);    
    }

</script>
<script type="text/javascript" src="../../scripts/home.js">
</script>
</body>
</html>