<!-- controller file is all_announcements.php -->
<!-- This is a view for displaying previously sent announcements-->
<!-- It's controller is "history.php"-->
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Announcements</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="../../styles/view_collection.css">
  <link href='https://fonts.googleapis.com/css?family=Bungee Shade' rel='stylesheet'>
</head>
<body>
  <header role="banner">
    <img style="width:100%;height:200px;margin:0;" src="../../image/saint%20francis%20of%20assisi.jpg">
  </header>
  <div class="topnav">
    <ul>
      <li><a href="../../?controller=reg_ops/register">Sign Up</a></li>
      <!-- This should later link to a user profile page -->
      <?php if(!isset($_SESSION['logged_in'])): ?>
        <li><a href="../../?controller=auth_ops/login_panel">Login</a></li>
      <?php elseif(isset($_SESSION['logged_in'])): ?>
        <li><a href="../../?controller=auth_ops/logout">logout</a></li>
        <li><a><?php echo $_SESSION['logged_in'] ?></a></li>
      <?php endif; ?>
      <li class="dropdown">
        <a href="javascript:void(0)" class="dropbtn">Activities</a>
        <div class="dropdown-content">
          <div class="row">
            
            <div class="column side1">

              <span>COMMUNITIES</span>
              <a href="#">Igede Catholic Community</a>
              <a href="#">Arewa Catholic Community</a>
              <a href="#">Niger Delta Communities</a>
              <a href="#">Igbo Catholic Community</a>
            </div>
            <div class="column middle1">
              <span>SOCITIES</span>
              <a href="#">Board of Lectors</a>
              <a href="#">St Vincent De Paul</a>
              <a href="#">Charismatic Renewal Movement</a>
            </div>
            <div class="column side1">   
              <span>Organizations</span>
              <a href="#">C.M.O</a>
              <a href="#">C.W.O</a>
              <a href="#">C.Y.O.N</a>
            </div>
          </div>
        </div>
      </li>

      <li class="dropdown">
        <a href="javascript:void(0)" class="dropbtn">Announcements</a>
        <div class="dropdown-content">
          <div class="row">

            <div class="column side1">
              <span>General Parish Announcements</span>
              <a href="../../?controller=announce_ops/general_view_con">View All</a>
              <?php if(isset($_SESSION['logged_in'])): ?>
                <a href="../../?controller=announce_ops/general_add_con">Add New</a>
                <a href="../../?controller=announce_ops/general_delete_con">Delete Some</a>
              <?php endif; ?>
            </div>

            <div class="column side1">
              <span>Marriage Banns</span>
              <a href="../../?controller=announce_ops/marriage_bann_show_con">View Banns</a>
              <?php if(isset($_SESSION['logged_in'])): ?>
                <a href="../../?controller=announce_ops/marriage_bann_add_con">Add New Bann</a>
                <a href="../../?controller=announce_ops/marriage_bann_del_con">Delete Bann</a>
              <?php endif; ?>

            </div>

            <div class="column side1">
              <span>Church Collections</span>
              <a href="../../?controller=announce_ops/collection_view_con">View Collections</a>
              <?php if(isset($_SESSION['logged_in'])): ?>
                <a href="../../?controller=announce_ops/collection_add_con">Add Collections</a>
                <a href="../../?controller=announce_ops/collection_delete_con">Delete Collections</a>
              <?php endif; ?>
            </div>

          </div>
        </div>
      </li>

      <li><a href="#">News</a></li>
      <li><a href="../../?controller=home/general_home">Home</a></li>

    </ul>
  </div>
  <main role="main">
    <marquee><span class="slide">SAINT FRANCIS CATHOLIC CHURCH GALADIMAWA</span></marquee>
    <div id="container">
      <div class="table">
       <div id="comments">
        <table>
         <caption><h1>CHURCH COLLECTIONS</h1></caption>



         <tr>
          <th>S/N</th>
          <th>Purpose of collection</th>
          <th>Date</th>
        </tr>

        <?php 
        $x = 1;
        foreach ($collection as $announcement): ?>


        <tr>
         
          <td><?php echo $x++ ?> </td>
          <td><?php echo $announcement["purpose"] ?> </td>
          <td><?php echo $announcement["date"] ?> </td>

        </tr>

        
      <?php endforeach; ?>
    </table>
  </div>
</div>
</div>
</main>
<footer role="footer">
  <div class="footer">
   &copy;Lawrant Group
 </div>
</footer>
<script>

	var myIndex = 0;

	carousel();

	function carousel() {
		var i;
		var x = document.getElementsByClassName("mySlides");
		for (i = 0; i < x.length; i++) {
			x[i].style.display = "none";  
		}
		myIndex++;
		if (myIndex > x.length) {myIndex = 1}    
			x[myIndex-1].style.display = "block";  
		setTimeout(carousel, 9000);    
	}
</script>

</body>
</html>