<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Church Announcement</title>
    <link rel="stylesheet" href="../../styles/marriage_ban_add.css">
    <link href='https://fonts.googleapis.com/css?family=Bungee Shade' rel='stylesheet'>
</head>
<body>
    <header role="banner">
        <img style="width:100%;height:200px;margin:0;" src="../../image/saint%20francis%20of%20assisi.jpg">
    </header>
    <div class="topnav">
        <ul>
            <li><a href="../../?controller=reg_ops/register">Sign Up</a></li>
            <!-- This should later link to a user profile page -->
            <?php if(!isset($_SESSION['logged_in'])): ?>
                <li><a href="../../?controller=auth_ops/login_panel">Login</a></li>
            <?php elseif(isset($_SESSION['logged_in'])): ?>
                <li><a href="../../?controller=auth_ops/logout">logout</a></li>
                <li><a><?php echo $_SESSION['logged_in'] ?></a></li>
            <?php endif; ?>
            <li class="dropdown">
              <a href="javascript:void(0)" class="dropbtn">Activities</a>
              <div class="dropdown-content">
                <div class="row">
                  
                  <div class="column side1">

                    <span>COMMUNITIES</span>
                    <a href="#">Igede Catholic Community</a>
                    <a href="#">Arewa Catholic Community</a>
                    <a href="#">Niger Delta Communities</a>
                    <a href="#">Igbo Catholic Community</a>
                </div>
                <div class="column middle1">
                    <span>SOCITIES</span>
                    <a href="#">Board of Lectors</a>
                    <a href="#">St Vincent De Paul</a>
                    <a href="#">Charismatic Renewal Movement</a>
                </div>
                <div class="column side1">   
                    <span>Organizations</span>
                    <a href="#">C.M.O</a>
                    <a href="#">C.W.O</a>
                    <a href="#">C.Y.O.N</a>
                </div>
            </div>
        </div>
    </li>

    <li class="dropdown">
      <a href="javascript:void(0)" class="dropbtn">Announcements</a>
      <div class="dropdown-content">
        <div class="row">

          <div class="column side1">
            <span>General Parish Announcements</span>
            <a href="../../?controller=announce_ops/general_view_con">View All</a>
            <?php if(isset($_SESSION['logged_in'])): ?>
              <a href="../../?controller=announce_ops/general_add_con">Add New</a>
              <a href="../../?controller=announce_ops/general_delete_con">Delete Some</a>
          <?php endif; ?>
      </div>

      <div class="column side1">
        <span>Marriage Banns</span>
        <a href="../../?controller=announce_ops/marriage_bann_show_con">View Banns</a>
        <?php if(isset($_SESSION['logged_in'])): ?>
          <a href="../../?controller=announce_ops/marriage_bann_add_con">Add New Bann</a>
          <a href="../../?controller=announce_ops/marriage_bann_del_con">Delete Bann</a>
      <?php endif; ?>

  </div>

  <div class="column side1">
    <span>Church Collections</span>
    <a href="../../?controller=announce_ops/collection_view_con">View Collections</a>
    <?php if(isset($_SESSION['logged_in'])): ?>
      <a href="../../?controller=announce_ops/collection_add_con">Add Collections</a>
      <a href="../../?controller=announce_ops/collection_delete_con">Delete Collections</a>
  <?php endif; ?>
</div>

</div>
</div>
</li>

<li><a href="#">News</a></li>
<li><a href="../../?controller=home/general_home">Home</a></li>

</ul>
</div>
<main role="banner">
    <div id="container">
        <marquee><span class="slide">SAINT FRANCIS CATHOLIC CHURCH GALADIMAWA</span></marquee>
        <div class="form">
            <form action="?controller=announce_ops/marriage_bann_add_con" method="POST">
                <center>  <lagend><h1 style="color:white;">MARRIAGE BANNS</h1></lagend></center>
                <!-- Catch error messages -->
                <?php if(!empty($successMessages)) :?>
                    <?php foreach($successMessages as $key => $message):?>
                        <div><span>Success:</span><?php echo $message ?></div>
                    <?php endforeach;?>
                <?php endif; ?>

                <?php if(!empty($errorMessages)):?>
                    <?php foreach($errorMessages as $key => $message): ?>
                        <div style="color:red"><span>Error:</span><?php echo $message; ?></div>
                    <?php endforeach; ?>
                <?php endif; ?>

                <input type="text" name="sponsus" placeholder='Sponsus (i.e., groom)'><br><br>
                <input type="text" name="sponsus_father" placeholder="Sponsus father (i.e., groom's Father)"><br><br>
                <input type="text" name="sponsus_mother" placeholder="Sponsus mother (i.e., groom's Mother)"><br><br>
                <input type="text" name="sponsus_native" placeholder="Sponsus native (i.e., groom's village address)"><br><br>

                <input type="text" name="sponsa" placeholder='Sponsa (i.e., bride)'><br><br>
                <input type="text" name="sponsa_father" placeholder="Sponsa father (i.e., bride's Father)"><br><br>
                <input type="text" name="sponsa_mother" placeholder="Sponsa mother (i.e., bride's Mother)"><br><br>
                <input type="text" name="sponsa_native" placeholder="Sponsa native (i.e., bride's village address)"><br><br>

                <select name="call_number">
                    <option value=""></option>
                    <option value="1st">1st</option>
                    <option value="2nd">2nd</option>
                    <option value="3rd">3rd</option>
                </select>
                
                <center><input type="submit" value="Add Marriage Bann"></center>
            </form>
        </div>
    </div>
</main>
<footer role="footer">
    <div class="footer">
       &copy;Lawrant Group
   </div>
</footer>
</body>
</html>